# ─────────────────────────────────────────────
#  PRODUCCION: Todo listo para Docker Hub
#  No necesitas archivos adicionales.
#  Solo Docker Compose y este archivo.
# ─────────────────────────────────────────────

services:
  frontend:
    image: ginolxdlol/vulnerable-colegio-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    image: ginolxdlol/vulnerable-colegio-backend:latest
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/vulnerable-colegio
      PORT: 5000
      NODE_ENV: production
      # Cambia esto por una clave segura en produccion real
      JWT_SECRET: ${JWT_SECRET:-vulnerable_colegio_secret_key_change_me}
      CLIENT_URL: http://localhost
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - uploads_data:/app/uploads

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mongo_data:
  uploads_data:

networks:
  app-network:
    driver: bridge
